### ISSUE TITLE
ISSUE #3: Top edge of wall is clipped off when it is on the bottom of the screen

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#109]
The top edge of walls facing down near the bottom of the screen have their top clipped off.  This is most noticeable while walking upwards, as the wall disappears much quicker than is expected based on the characters movement.

Most likely it is due to the wall clipping with the camera.

This can be seen at the lower left corner of the attached file.
https://i.imgur.com/3s0Tsaa.gifv

Tested on 1280 x 720 and 1600x900 resolutions

**Comment by sma7560** [comment]
Camera angle and clipping settings have been adjusted.
