### ISSUE TITLE
SUGGESTION #4: World/View scale change

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#110]
Large zoomed in rooms allow player to completely miss fancy details such as the current room being a throne room vs it being a random empty space.  This also makes the game harder to navigate, as there are very few points of reference that are memorable in many of the larger rooms.  Additionally this made it difficult to locate opposing players anywhere except in the narrow hallways whey they were not launching attacks.

Zooming out the camera can make the world feel more full without needing to add more elements to it to fill the blank spaces.  This would also give the players a larger view range, making it easier to locate opponents.

**Comment by SusanSuY** [comment]
Camera has been changed to an isometric view, which displays much more of the map on screen.
