### ISSUE TITLE
SUGGESTION #5: Provide more information on stats

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#111]
Providing more information on what/how the stats do/work is needed so players can understand how the game mechanics work.  Without this info, it is very difficult for players who like to optimize their gameplay to get immersed in the game for extended periods of time.

ex. Inform player what a 1 point increase in Attack speed actually does.  
Does it: -remove 1% of a cooldown? 
-remove 1 second of cooldown? 
-shorten time to cast an attack? 
-make attacks move faster?

also ex: what does this ______  attack actually do? (death ball, etc.)

Alternatively provide some way for the player to know which stats are 'best' for their intended play style, such as tips in the waiting screens, or providing 'preset' roles that can be modified (ex. a button labeled tank that raises relevant stats (defense etc.) and selects defensive skills)

**Comment by sma7560** [comment]
Additional info has been added to the pre-game prephase UI
