### ISSUE TITLE
SUGGESTION #7: Inform player of connection status

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#113]
When connecting to a game it should inform the player when a connection succeeds or fails (an incorrectly typed IP currently does not inform you that the game doesn't exist)

**Comment by SusanSuY** [comment]
Linked to issue #44

**Comment by SusanSuY** [comment]
Issue #44 closed. Error messages have been added to the main menu.
