### ISSUE TITLE
SUGGESTION #8: Inform player of game events

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#114]
It is difficult to understand the state of the game as there is no way to know which team is winning/has the artifact etc. 

An addition that may solve this would be a scoreboard that informs the player when a game event occurs, such as another player (or their player) dies, the artifact is picked up, points are obtained, overall score etc.

**Comment by SusanSuY** [comment]
We are planning to add a scoreboard and game event announcements.

Scoreboard will display each player's score,

Game event announcements will include:
- Player # acquired ale!
- Player # scored an ale!
- Boss enemy has appeared in the kitchen!
- Player # has died!

**Comment by SusanSuY** [comment]
Event announcements added, still need to add scoreboard.

**Comment by SusanSuY** [comment]
Scoreboard added in commit [2bcc5da](https://github.com/lawlbit/Wizards_Pub_Crawl/commit/2bcc5da6ee955edfe4f20ebc1b24b2a52fec20c6).
