### ISSUE TITLE
ISSUE #9: balance attacks/magic

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#115]
Currently the games balance is heavily skewed in one direction: 
1st skill - does 2 dmg, 2 sec cooldown
	needs 50 seconds to beat an enemy assuming perfect accuracy
2nd skill - does 100+ dmg, 20 second cooldown
	1 shots anything
3rd  skill- unclear, buffs player?
melee attacks - minimal damage but require the player to very close to the enemy (optimal range for 2nd skill)

there is never any reason to use the 1st attack, it is faster to wait for the 2nd attack to recharge than to focus on the still slow rate of fire 1st attack.

Increasing the damage of the first attack and melee, maybe to as high as 20-30 or even higher could allow for more varied strategies even without adding in brand new skills.  More testing will be required for a balanced experience.

**Comment by SusanSuY** [comment]
We had made many changes to balancing in the game
