### ISSUE TITLE
SUGGESTION #10: Allow for pre-configured point distributions

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/Wizards_Pub_Crawl#116]
It is very pressuring to understand/select point distributions/spells/character models in the short period of time before a game begins.  Allowing players to pre-configure these outside of the game ready screen or to save/load sets can allow for more focus on customization without the time constraint.

This can allow for shorter ready times, allow players to have multiple strategies on hand and allow players to search for that perfect set.

Perhaps this can be used to switch 'class' between lives.

**Comment by SusanSuY** [comment]
We have changed attributes to be pre-determined based on the character model selected, therefore there is no longer a need to pre-configure attributes outside of the match.
