### ISSUE TITLE
Issue #6: Shadows seem off for corners of walls.

### ISSUE THREAD

**Issue by NathanCoit** [lawlbit/Wizards_Pub_Crawl#122]
At the corners of walls, a shadow stretches out which doesn't seem like it should be.
![image](https://user-images.githubusercontent.com/26461233/50854706-ca5fcc80-1353-11e9-8a54-6a1d396f3e3e.png)

**Comment by SusanSuY** [comment]
Camera angle has been changed, so this is no longer an issue.
