### ISSUE TITLE
Suggestion: Additional Volume Settings

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/Wizards_Pub_Crawl#123]
It would be helpful if there was an option to completely mute/unmute the game volume without dragging the slider. Also a numbered indicator (either percentage or absolute) could be a useful addition. This could be in the slider itself or above beside the "Volume" text. This way users have more control and are aware of what the resulting action is.

**Comment by SusanSuY** [comment]
Added mute/unmute button. Also added percentage text that pops up when the slider is being dragged.
