### ISSUE TITLE
Suggestion: Join game by pressing Enter or join automatically on Copy/Paste

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/Wizards_Pub_Crawl#132]
After entering the IP address, the user has to click "Join Game". It would be nice if the user could simply press enter after typing in the IP address. In addition, if the user copy/pastes a IP address the game should try to join automatically following the paste action. This makes the process of joining a game quicker/easier.

**Comment by SusanSuY** [comment]
Pressing enter now allows the player to join the match. We have decided not to allow automatic joining upon pasting an IP, as this behaviour may be unpredictable. The user may want to change the IP slightly after pasting it, in case the copy and pasting did not go as expected.
