### ISSUE TITLE
SUGGESTION #1: Attack animation could be faster

### ISSUE THREAD

**Issue by SullivanStobo** [lawlbit/Wizards_Pub_Crawl#137]
At the moment attacking (by pressing space) feels very slow and unresponsive. Speeding the animation up could fix this. Also locking player movement during this animation would make sense.

**Comment by SullivanStobo** [comment]
To add to this, clicking to attack would also be nice. Unless there is other plans for what clicking does.

**Comment by SusanSuY** [comment]
Duplicate of issue #88 for attack animation speed. Clicking to attack is under consideration, but low priority.

**Comment by lawlbit** [comment]
Closing as the animation lag has been addressed.
