### ISSUE TITLE
SUGGESTION #6: Rotating the camera could help to confusion between floors and walls

### ISSUE THREAD

**Issue by SullivanStobo** [lawlbit/Wizards_Pub_Crawl#142]
The sort of straight on view being used at the moment leads to some confusion about what is the floor and what is the wall. If the camera angle was changed, perhaps it would this issue.

**Comment by lawlbit** [comment]
New camera angle solves the issue as it the close plane for the frustum of the camera allows the player to see through close walls and the angle minimizes confusion.
