### ISSUE TITLE
ISSUE #9: Bouncing bolt bounces before walls

### ISSUE THREAD

**Issue by SullivanStobo** [lawlbit/Wizards_Pub_Crawl#145]
![thing](https://user-images.githubusercontent.com/26728955/50931537-dcfc0380-1430-11e9-93eb-2d9cf00fe344.png)

As in the picture, it seems to bounce before the wall below.

**Comment by SusanSuY** [comment]
This seemed like an issue previously due to the camera angle and wall culling. After the camera angle change, this issue isn't visible anymore.
