### ISSUE TITLE
Suggestion: Show image of what an artifact is.

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/Wizards_Pub_Crawl#163]
Before setting the user to go collect an artifact. It helps the user see what their goal will look like.

**Comment by SusanSuY** [comment]
@Chaozs maybe add this to the How to Play? (related to issue #43)

**Comment by SusanSuY** [comment]
We believe this is no longer necessary. Additionally, the background of the main menu displays what the ale looks like.
