### ISSUE TITLE
SUGGESTION: Additional Settings Other Than Volume

### ISSUE THREAD

**Issue by wildingelijah** [lawlbit/Wizards_Pub_Crawl#169]
#### Context
Unsure what you might need to control but upon visiting the settings menu it appears to be very barren with just the volume slider.

#### High Level Suggestions
Adding additional settings or changing menu design to make it look less empty as a whole.

### Rationale
To improve the appearance and versatility (being able to adjust settings) of the game.

**Comment by SusanSuY** [comment]
There are plans to add master volume, background music, and sound effects volume settings (3 audio settings in total). This will happen after sound effects have been fully integrated into the game.

**Comment by SusanSuY** [comment]
Blocked by issue #36. Need to wait for sound effects to be added in order to add more audio settings.

**Comment by SusanSuY** [comment]
Added slider for sound effects.
