### ISSUE TITLE
SUGGESTION: Add More Skills and Balance Cooldowns

### ISSUE THREAD

**Issue by wildingelijah** [lawlbit/Wizards_Pub_Crawl#177]
#### Context
Upon playing the game a couple times I became bored of the lack of skills and the long length of cooldowns. Only having the choice of 3 skills was sad and the cooldowns need balancing for to ensure that they are not too powerful but also so that each cool down is not too long. 

#### High Level Suggestions
My suggestion would be to add more skills and to spend lots of time balancing gameplay.

### Rationale
In order for the game to function well (be a challenge for the player but also not be too hard) balancing is always essential to make sure this can happen.

**Comment by lawlbit** [comment]
Added more skills, still need to create one more skill. Balancing on going.
