### ISSUE TITLE
SUGGESTION: Add more detail to main menu

### ISSUE THREAD

**Issue by wildingelijah** [lawlbit/Wizards_Pub_Crawl#182]
#### Context
Main Menu looks a little blank with all text on left and then clear area to the right. When entering the game, the player should be inspired by what they see and it just felt as if there was something lacking.

#### High Level Suggestions
Add some art or something that references your dungeon instead of plain area.

### Rationale
The main reasoning is purely to intrigue the player and make them want to play even more than they already do!

**Comment by SusanSuY** [comment]
Already planned. Initially used coloured background as a placeholder since we did not have a dungeon map to show in the main menu background yet.

**Comment by SusanSuY** [comment]
Background of main menu has been updated in commit [7bc115f](https://github.com/lawlbit/GameNamePlaceHolder/commit/7bc115f900842cc9f8621ae5e5ca42cbd537678f), but not yet finalized as our dungeon map is not finalized just yet.

**Comment by SusanSuY** [comment]
Main menu background is now polished and finalized.
