### ISSUE TITLE
ISSUE: Hitboxes and Hit Registration Need Work

### ISSUE THREAD

**Issue by wildingelijah** [lawlbit/Wizards_Pub_Crawl#186]
#### Context
Skills and enemies hit from too far away. This could be seen as a suggestion but my thought is that it will make the game poorly balanced.
#### Expected Output
Shorter ranges on skills.
#### Actual Output
Skills seem to proceed forever so could technically hit across the entire map.
### Steps to Reproduce
1. Play game.
2. Use a skill that shoots a projectile.
### Bug Appearance
Whenever skills are used that have any sort of range this bug occurs as the projectiles will travel forever. 
### System Configuration
Resolution: Full screen
OS: Windows
Controller Type: Mouse & Keyboard

**Comment by SusanSuY** [comment]
Projectiles no longer last forever.
