### ISSUE TITLE
2 players on local machine joined and pre-phase show # of player: 2, but the game shows waiting for players forever.

### ISSUE THREAD

**Issue by Codhog** [lawlbit/Wizards_Pub_Crawl#190]
After it happened, I haven't been able to reproduce the error.  So it could be a small glitch happen for 2 instances running on local machine.

**Comment by SusanSuY** [comment]
Most likely race condition regarding pre-phase. I can take a look into this.

**Comment by SusanSuY** [comment]
Possibility:
- Both players connect almost at the same time.
- In Player 2, OnServerConnect() finishes first, thus calling UpdatePrephase() first.
- In Player 1, StartUpHost() finishes after, thus calling StartPrephaseWaitingRoom() after.
This will cause the state to be WaitingRoom, and UpdatePrephase() is never called again to correct the state.

Still need to debug to check.

Possible solution: call UpdatePrephase() periodically.

**Comment by SusanSuY** [comment]
Took about 50 tries to reproduce this:

![image](https://user-images.githubusercontent.com/15915128/54330871-cff4bf80-45ed-11e9-981b-c28c232ae859.png)

**Comment by SusanSuY** [comment]
Root cause: pressing "Create Dungeon" more than once causes this issue.

**Comment by SusanSuY** [comment]
Now, when clicking "New Match", the button is no longer interactable, preventing player from pressing it twice.
