### ISSUE TITLE
Create some visual boundary around spawn locations

### ISSUE THREAD

**Issue by SusanSuY** [lawlbit/Wizards_Pub_Crawl#194]
In order to let players know where their spawn location is marked (so they know where their safe zone is), there should be a visual boundary around their spawn location.

Possibly need to colour code each spawn point for each player as well in order to differentiate between the spawn locations. Please check GetPlayerColour() in HeroManager.cs.

**Comment by sma7560** [comment]
Map updated to visualize spawn.
