### ISSUE TITLE
Fix Sword Decoration Error in Map

### ISSUE THREAD

**Issue by SusanSuY** [lawlbit/Wizards_Pub_Crawl#203]
Error for one of the sword decorations on the map:

![image](https://user-images.githubusercontent.com/15915128/54842358-1ca06080-4ca8-11e9-873f-024f5e79708c.png)

**Steps to reproduce:**
1. Run the game from Unity editor
2. Error will popup immediately in console output

**Comment by sma7560** [comment]
Fixed
