### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by SusanSuY** [lawlbit/Wizards_Pub_Crawl#32]
Implement objectives
- **(NOT DONE)** Come up with objectives and the score associated with completing them
- **(NOT DONE)** Layout the code for objectives
- **(NOT DONE)** Integrate it into the UI
- **(NOT DONE)** Ensure that objectives are updated throughout the match as required (make sure there are always objectives laid out so players have a goal at all times, ensure they are updated as players complete them, etc.)

**DEADLINE:** Dec 18, 2018 @ 11:59pm

**Comment by sma7560** [comment]
Cut from final build for the time being
