### ISSUE TITLE
Bug Report #1: Melee Attack is super weak in comparison to the damage the squares give in that range. Once in a melee battle begins with a square you can virtually not kill him and will almost certainly die

### ISSUE THREAD

**Issue by zpalantz** [lawlbit/Wizards_Pub_Crawl#45]
Melee Attack is super weak in comparison to the damage the squares give in that range. Once in a melee battle begins with a square you can virtually not kill him and will almost certainly die

**Comment by SusanSuY** [comment]
We have removed melee attacks from the game.
