### ISSUE TITLE
Bug Report #2: Player 1 upgraded attack speed to its maximum capacity while player 2 had the minimum possible attack speed. However, every attack (Melee and Magic) were the same speed for both players.

### ISSUE THREAD

**Issue by zpalantz** [lawlbit/Wizards_Pub_Crawl#46]
Player 1 upgraded attack speed to its maximum capacity while player 2 had the minimum possible attack speed. However, every attack (Melee and Magic) were the same speed for both players.

**Comment by SusanSuY** [comment]
We have removed attack speed as a stat.
