### ISSUE TITLE
Bug Report #7: If you use the magic attack death ball and continue to move in the direction of the attack you will end up quickly killing yourself due to the death ball being so slow

### ISSUE THREAD

**Issue by zpalantz** [lawlbit/Wizards_Pub_Crawl#51]
If you use the magic attack death ball and continue to move in the direction of the attack you will end up quickly killing yourself due to the death ball being so slow.

**Comment by lawlbit** [comment]
This issue will be looked to when it comes to balancing, currently however the skill is working as intended.
