### ISSUE TITLE
Bug Report #8: Player 2 upgraded magical damage to its maximum capacity while Player 1 had the minimum possible magical damage. However, both players inflicted the same magical damage to the squares

### ISSUE THREAD

**Issue by zpalantz** [lawlbit/Wizards_Pub_Crawl#52]
Player 2 upgraded magical damage to its maximum capacity while Player 1 had the minimum possible magical damage. However, both players inflicted the same magical damage to the squares.

**Comment by SusanSuY** [comment]
This has been fixed. All stats are now used in damage calculation.
