### ISSUE TITLE
Bug Report #10: There is no game play difference between selecting characters. For example no statistical difference in magical strength between a Mage and a King when using the same magical attacks on the squares

### ISSUE THREAD

**Issue by zpalantz** [lawlbit/Wizards_Pub_Crawl#54]
There is no game play difference between selecting characters. For example no statistical difference in magical strength between a Mage and a King when using the same magical attacks on the squares.

**Comment by SusanSuY** [comment]
Stats are now used in calculation of damage, and are now pre-determined based on the character model chosen. Therefore, the varying stats of different characters now result in gameplay differences between the available characters.
