### ISSUE TITLE
[Damian] ISSUE #2: Attacks escape border of the room

### ISSUE THREAD

**Issue by DamianAngelone** [lawlbit/Wizards_Pub_Crawl#66]
**Description**
When the character is right against the wall, the attacks can leave the room and travel into undesignated areas or other rooms.

**Steps to Reproduce**
- Walk up to any wall
- Position our skill shot to angle through the wall
- Fire your attack
- Note that the attack can be see out of bounds
- Also note that a second player can see this attack re-enter into another room

**Appearance of Bug**
This bug can occur on any wall in the game with any attack.

**Suggested Solutions**
This issue is occurring not because there is no collision on the wall/shots, but because the character's wand is past the wall's collider when the player is right against it. This can be resolved by extending the character's collider to include the wand, to prevent it from clipping through the wall.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by SusanSuY** [comment]
Has been fixed. Skills will no longer move through walls.
