### ISSUE TITLE
[Damian] ISSUE #3: After Killing a Player, the mission doesn't get "ticked"

### ISSUE THREAD

**Issue by DamianAngelone** [lawlbit/Wizards_Pub_Crawl#67]
**Description**
The checkbox beside the mission doesn't present proper feedback when the mission is completed.

**Steps to Reproduce**
- Locate a player
- Kill the player
- Note that the mission doesn't get updated as completed

**Appearance of Bug**
This mission will never get updated no matter how many times a player is killed.

**Suggested Solutions**
This bug just seems like a feature that has yet to be implemented yet, but I will mention it in case that's not the case. In case it's not, it's probably just an error in your logic.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by SusanSuY** [comment]
Result of objectives not being implemented yet #32

**Comment by sma7560** [comment]
We have cut Missions from the final build of the game
