### ISSUE TITLE
[Damian] ISSUE #4: When a player has an artifact, it is not visible for the other player

### ISSUE THREAD

**Issue by DamianAngelone** [lawlbit/Wizards_Pub_Crawl#68]
**Description**
While the artifact is hovering over the head of Player 1, Player 2 cannot see it.

**Steps to Reproduce**
- Player 1 locates the artifact
- Player 1 obtains the artifact
- Note that Player 2 cannot see the artifact over Player 1's head

**Appearance of Bug**
This bug is present in all scenarios that I tested; an obtained artifact is never seen by the other player(s).

**Suggested Solutions**
This seems like a networking issue. I suggest checking all data that is shared amongst the players and ensure that the obtained artifact is part of it.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by SusanSuY** [comment]
Sounds like a networking issue.

**Comment by lawlbit** [comment]
This issue has been fixed with the commit 21d443bc3f9d9393c197ccc3360b67a57eebf86a
