### ISSUE TITLE
[Damian] SUGGESTION #6: Assign Ability to Different Keys 

### ISSUE THREAD

**Issue by DamianAngelone** [lawlbit/Wizards_Pub_Crawl#70]
**Targeted Mechanic**
Remap certain keys to make gameplay more smooth.

**Suggestion**
Assign the characters' abilities to different keys (such as the num pad).

**Significance**
When playing with the Mouse and WASD, it's hard to choose attacks during movement. This can help simplify the controls and make it easier for the player to initially learn the game. Also, fluent controls will add to a proper flow for your game.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by SusanSuY** [comment]
Added in commits [5013d47](https://github.com/lawlbit/Wizards_Pub_Crawl/commit/50134d7074f7c6c961338aa24a5e393d6c34c1d5) and [f8f9563](https://github.com/lawlbit/Wizards_Pub_Crawl/commit/f8f956335dd8c662ad6027e5cf7ce69910f0cf38)
