### ISSUE TITLE
SUGGESTION: Add some time to/Reset, the lobby timer when a new player joins 

### ISSUE THREAD

**Issue by KarnvirBining** [lawlbit/Wizards_Pub_Crawl#86]
If the timer doesn't reset then the newest player to join might not have time to allocate their attribute points.

**Comment by KarnvirBining** [comment]
If the timer doesn't reset then the newest player to join doesn't have time to allocate attribute points.

**Comment by SusanSuY** [comment]
Currently planning to add another screen for Waiting Room state so that Player 1 cannot start editing their character until all players have joined to ensure fairness of the pre-phase stage.

**Comment by SusanSuY** [comment]
Waiting room screen has been added, so both players now get the same amount of time for setup.
